from collections.abc import AsyncIterator, Callable
from typing import BinaryIO, Protocol, TypeAlias

from fz_manager_plus.domain.messages import BlankMessage, FzMessage, LoginResponse

Progress: TypeAlias = Callable[[int], None] | None


class ZoneAPI(Protocol):
    visit_secret: str | None
    user_token: str | None

    async def login(self, reconnected: bool = False) -> LoginResponse: ...
    async def start_instance(self, region: str, version: str, save: str) -> None: ...
    async def stop_instance(self, launch_id: int) -> None: ...
    async def send_command(self, launch_id: int, command: str) -> None: ...
    async def toggle_mod(self, mod_id: int, enabled: bool) -> None: ...
    async def delete_mod(self, mod_id: int) -> None: ...
    async def upload_mod(
        self, name: str, file: BinaryIO, size: int, progress: Progress = None
    ) -> None: ...
    async def upload_save(
        self, name: str, file: BinaryIO, size: int, slot: str, progress: Progress = None
    ) -> None: ...
    async def delete_save_slot(self, slot: str) -> None: ...
    async def download_save_slot(
        self, slot: str, file_path: str, progress: Progress = None
    ) -> None: ...
    async def aclose(self) -> None: ...


class ZoneSocket(Protocol):
    async def connect(self) -> None: ...
    def messages(self) -> AsyncIterator[FzMessage | BlankMessage]: ...
    async def close(self) -> None: ...
